// <auto-generated />
namespace Facturador.Module.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Facturar4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Facturar4));
        
        string IMigrationMetadata.Id
        {
            get { return "202109142256244_Facturar4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
